<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
    <PublishWithAspNetCoreTargetManifest>false</PublishWithAspNetCoreTargetManifest>
  </PropertyGroup>

  <Target Name="CheckForNpm" BeforeTargets="NpmInstall">
    <Exec Command="npm -v" ContinueOnError="true">
        <Output TaskParameter="ExitCode" PropertyName="ErrorCode" />
    </Exec>
    <Error Condition="'$(ErrorCode)' != '0'" Text="Debe instalar NPM para compilar este proyecto" />
  </Target>

  <Target Name="NpmInstall" BeforeTargets="BuildCSS" Inputs="package.json" Outputs="$(NpmLastInstall)">
      <Exec Command="npm install" />
      <Touch Files="$(NpmLastInstall)" AlwaysCreate="true" />
  </Target>

  <Target Name="Tailwind" BeforeTargets="PreBuildEvent">
      <Exec Command="npm run build:css" />
  </Target>

  <Target Name="TailwindDebug" BeforeTargets="Compile" Condition="'$(Configuration)' == 'Debug'">
      <Exec WorkingDirectory="$(ProjectDir)" Command="npm run build:css" />
  </Target>

  <Target Name="TailwindRelease" BeforeTargets="Compile" Condition="'$(Configuration)' == 'Release'">
      <Exec EnvironmentVariables="NODE_ENV=production" Command="npm run release:css" />
  </Target>
  <ItemGroup>
    <Content Remove="wwwroot\assets\icono-error.svg" />
    <Content Remove="wwwroot\img\79662242firma.jpg" />
  </ItemGroup>
  
  <ItemGroup>
    <Watch Include="./Styles/tailwind.css" Exclude="./wwwroot/**/*;obj\**\*;bin\**\*" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="copilot-instructions.md" />
  </ItemGroup>

  <ItemGroup>
    <None Include=".github\copilot-instructions.md" />
    <None Include=".github\instructions\backend.instructions.md" />
    <None Include="wwwroot\assets\feather-sprite.svg" />
    <None Include="wwwroot\assets\icono-error.svg" />
    <None Include="wwwroot\assets\iconos.svg" />
    <None Include="wwwroot\img\boton-captura.svg" />
    <None Include="wwwroot\img\izquierda-pulgar.svg" />
    <None Include="wwwroot\Plantilla\pqr_portal_administrativo.html" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.16.0" />
    <PackageReference Include="Blazored.Toast" Version="3.2.2" />
    <PackageReference Include="BlazorInputFile" Version="0.2.0" />
    <PackageReference Include="BlazorPro.Spinkit" Version="1.2.0" />
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="EPPlus" Version="7.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.HttpClient" Version="3.2.0-preview3.20168.3" />
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="8.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Components.QuickGrid" Version="8.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
    <PackageReference Include="Microsoft.Azure.Storage.Blob" Version="11.2.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="6.0.7" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.61.3" />
    <PackageReference Include="Microsoft.PowerBI.Api" Version="4.14.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="PuppeteerSharp" Version="2.0.4" />
    <PackageReference Include="StackifyMiddleware" Version="3.0.5.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Pages\CompraPin\ComfirmacionCompra\" />
    <Folder Include="Pages\CompraPin\DatosPersonales\" />
    <Folder Include="Pages\CompraPin\Categorias\" />
    <Folder Include="Pages\CompraPin\FacturacionElectronica\" />
    <Folder Include="Pages\CompraPin\Operaciones\" />
    <Folder Include="Pages\CompraPin\ResumenCompra\" />
    <Folder Include="Pages\CompraPin\Resumen\" />
    <Folder Include="Pages\CompraPin\Tramite\" />
    <Folder Include="Pages\CompraPin\Blog\" />
	<Folder Include="Pages\CompraPinCDA\DatosPersonalesCDA\" />
	<Folder Include="Pages\CompraPinCDA\CategoriasCDA\" />
	<Folder Include="Pages\CompraPinCDA\TramiteCDA\" />
    <Folder Include="Pages\CompraPin\Tramite\TramiteCrc\" />
	  <Folder Include="Pages\CompraPin\Tramite\SeleccionCategorias\" />
  </ItemGroup>

  <ProjectExtensions>
    <VisualStudio>
      <UserProperties appsettings_1json__JsonSchema="" />
    </VisualStudio>
  </ProjectExtensions>

</Project>